### ISSUE TITLE
Clip.py hardcodes reference to author's filesystem.

### ISSUE THREAD

**Issue by mopierotti** [zer0int/CLIP-XAI-GUI#2]
(Thanks for making this! I'm excited to play around with it)

I had to track this issue down and change the path to get my install working.
https://github.com/zer0int/CLIP-XAI-GUI/blob/1434fb3997039d4914e405084451fc5238698041/CLIP/clip/clip.py#L95.

I also had to replace the references to `'python'` in `run_clipapp.py` to `sys.executable`. Presumably because I installed the packages with venv.

**Comment by zer0int** [comment]
Thank you very much for reporting that! Can't believe I didn't change that for the commit - fixed that now!

Also, thank you for the heads up about venv - indeed, I don't use any, so I never realized this was the case.
I fixed both issues now. 

Hope you enjoy playing with CLIP and watching it 'rant' about your images! =)
